version: "3"

services:

  redis:
    image: "redis:alpine"
    ports: ["6379"]
    networks:
      - back

  publisher:
    image: "oterrien/publisher:2.0"
    ports:
      - "5000:8080"
    networks:
      - back
    depends_on:
      - redis
    environment:
      ENV: development

  consumer:
    image: "oterrien/consumer:2.0"
    networks:
      - back
    depends_on:
      - redis

networks:
  back:
