version: "3"

services:

#  rabbitmq:
#    image: "rabbitmq:alpine"
#    ports:
#      - "5672:5672"
#    environment:
#      AMPQ_ADDRESS: "amqp://rabbitmq:5672"

  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"

  publisher:
    image: "oterrien/publisher:3.0"
    ports:
      - "5000:8080"
    links:
      - rabbitmq
    environment:
      ENV: "development"
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"

  consumer:
    image: "oterrien/consumer:3.0"
    links:
      - rabbitmq
    environment:
      ENV: "development"
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"
